name: deploy-web
on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: jogo-memoria
          tags: latest
          registry: ghcr.io/adilsonoj
          dockerfile: Dockerfile
          username: adilsonoj
          password: ${{ secrets.GH_TOKEN }}

      # - name: executing remote ssh commands using password
      #   uses: appleboy/ssh-action@v0.1.8
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USER }}
      #     # password: ${{ secrets.PASSWORD }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       cd /etc/prod
      #       cat .docker-pass/gh_token | sudo docker login ghcr.io --username adilsonoj --password-stdin
      #       sudo docker compose pull cartoon-web
      #       sudo docker compose up -d cartoon-web