name: deploy-web
on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: jogo-memoria
          tags: latest
          registry: ghcr.io/adilsonoj
          dockerfile: Dockerfile
          username: adilsonoj
          password: ${{ secrets.GH_TOKEN }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd /etc/app
            sudo docker compose pull jogo-memoria-web
            sudo docker compose up -d jogo-memoria-web